import assert from 'node:assert/strict';
import test from 'node:test';

import { canonicalize, digestOf, parseStrict, sha256Hex } from '../src/canonical';
import * as fixtures from '../src/fixtures';

/**
 * The schema set is generated by the Rust crate; this side hashes the checked-in file with its
 * own canonical JSON and digest, which is the cross-language half of `contractDigest`.
 */
test('the contract digest is the digest of the checked-in schema set', () => {
  const bytes = fixtures.loadBytes('schema-set.json');
  const text = Buffer.from(bytes).toString('utf8');
  assert.ok(text.endsWith('\n'), 'the file is the canonical set plus one newline');
  const canonical = text.slice(0, -1);
  const recorded = fixtures.load('contract-digest.json') as Record<string, unknown>;
  assert.equal(sha256Hex(canonical), recorded.contractDigest);
  assert.equal(canonical.length, recorded.schemaSetBytes);
  // ... and the file really is canonical JSON: reserializing it changes nothing.
  assert.equal(canonicalize(parseStrict(canonical)), canonical);
  assert.equal(digestOf(parseStrict(canonical)), recorded.contractDigest);
});

test('the contract digest survives reformatting and changes when a schema changes', () => {
  const set = parseStrict(
    Buffer.from(fixtures.loadBytes('schema-set.json')).toString('utf8').slice(0, -1),
  ) as Record<string, unknown>;
  const recorded = fixtures.load('contract-digest.json') as Record<string, unknown>;
  const pretty = parseStrict(JSON.stringify(set, null, 4));
  assert.equal(digestOf(pretty), recorded.contractDigest, 'pretty printing is not a change');

  const types = set.types as Record<string, unknown>[];
  const renamed = structuredClone(set);
  ((renamed.types as Record<string, unknown>[])[0]!.fields as Record<string, unknown>[])[0]!.name =
    'sessionIdentifier';
  assert.notEqual(digestOf(renamed), recorded.contractDigest, 'a renamed field is a change');

  const widened = structuredClone(set);
  for (const limit of widened.limits as Record<string, unknown>[]) {
    if (limit.name === 'maxAgents') limit.value = 8;
  }
  assert.notEqual(digestOf(widened), recorded.contractDigest, 'a widened bound is a change');

  const dropped = structuredClone(set);
  (dropped.types as unknown[]).pop();
  assert.notEqual(digestOf(dropped), recorded.contractDigest, 'a dropped type is a change');
  assert.ok(types.length >= 50, 'the schema set should stay broad');
});

test('the schema set publishes the limits this package enforces', async () => {
  const set = parseStrict(
    Buffer.from(fixtures.loadBytes('schema-set.json')).toString('utf8').slice(0, -1),
  ) as Record<string, unknown>;
  const limits = new Map(
    (set.limits as Record<string, unknown>[]).map((limit) => [
      limit.name as string,
      limit.value as number,
    ]),
  );
  const workers = await import('../src/workers');
  const media = await import('../src/media');
  const scalar = await import('../src/scalar');
  const canonical = await import('../src/canonical');
  assert.equal(limits.get('maxAgents'), workers.MAX_AGENTS);
  assert.equal(limits.get('maxPorts'), workers.MAX_PORTS);
  assert.equal(limits.get('maxRateRoles'), workers.MAX_RATE_ROLES);
  assert.equal(limits.get('maxStimuliPerOperation'), workers.MAX_STIMULI);
  assert.equal(limits.get('maxRewardsPerOperation'), workers.MAX_REWARDS);
  assert.equal(limits.get('maxButtons'), workers.MAX_BUTTONS);
  assert.equal(limits.get('maxAxes'), workers.MAX_AXES);
  assert.equal(limits.get('maxAcknowledge'), workers.MAX_ACKNOWLEDGE);
  assert.equal(limits.get('maxMessageCodePoints'), workers.MAX_MESSAGE_CODE_POINTS);
  assert.equal(limits.get('maxViews'), media.MAX_VIEWS);
  assert.equal(limits.get('maxViewDimension'), media.MAX_VIEW_DIMENSION);
  assert.equal(limits.get('maxSampleFrames'), media.MAX_SAMPLE_FRAMES);
  assert.equal(limits.get('maxAudioStreams'), media.MAX_AUDIO_STREAMS);
  assert.equal(limits.get('maxTypedValueBytes'), scalar.MAX_TYPED_VALUE_BYTES);
  assert.equal(limits.get('maxEnvelopeBytes'), canonical.MAX_ENVELOPE_BYTES);
  const extensions = await import('../src/extensions');
  assert.equal(limits.get('maxSlots'), extensions.MAX_SLOTS);
});

test('the closed enums this package knows are the ones the schema set declares', async () => {
  const set = parseStrict(
    Buffer.from(fixtures.loadBytes('schema-set.json')).toString('utf8').slice(0, -1),
  ) as Record<string, unknown>;
  const enums = new Map(
    (set.enums as Record<string, unknown>[]).map((entry) => [
      entry.name as string,
      entry.members as string[],
    ]),
  );
  const workers = await import('../src/workers');
  const rpc = await import('../src/rpc');
  assert.deepEqual(enums.get('ErrorCode'), [...rpc.ERROR_CODES]);
  assert.deepEqual(enums.get('MutationCertainty'), [...rpc.MUTATION_CERTAINTIES]);
  assert.deepEqual(enums.get('Role'), [...workers.ROLES]);
  assert.deepEqual(enums.get('WorkerState'), [...workers.WORKER_STATES]);
  assert.deepEqual(enums.get('Recovery'), [...workers.RECOVERY]);
  assert.deepEqual(enums.get('Determinism'), [...workers.DETERMINISM]);
  assert.deepEqual(enums.get('AxisRange'), [...workers.AXIS_RANGES]);
  assert.deepEqual(enums.get('EpisodeRequestKind'), [...workers.EPISODE_REQUEST_KINDS]);
});
