//! The legacy Game Boy composition's registered schemas and declarations (PROF-02a).
//!
//! [`legacy-gameboy-v1`] is the contract. The operator decided on 2026-09-23 that the live fly
//! is ported onto the session framework as a declared legacy profile rather than kept outside
//! it; this module is the machine-readable half of that decision.
//!
//! Nothing here is a generic session type. Every value below travels inside a `TypedValue`
//! (whose [`SchemaRef`] names one of [`PAYLOAD_SCHEMAS`]) or is a document an `AssetRef` or the
//! composition digest names. The generic types in [`crate::workers`] stay free of console
//! state, which is what `workers-v1` section 6 and ENV-01's acceptance require.
//!
//! - A **payload schema** is a declaration `(id, version, source, fields)`. Its `SchemaRef`
//!   digest is the SHA-256 of that declaration's canonical JSON, so the reference changes when
//!   a field, kind or constraint does and not when this file is reformatted -- the rule
//!   `contractDigest` follows for the session schema set.
//! - The **legacy profile** `gameboy-legacy-fafb-v783-v1` is one fixed document. Its
//!   `AssetRef.digest` is the SHA-256 of its canonical JSON ([`profile_digest`]).
//! - The **legacy composition** declaration carries everything that is behaviour but is not
//!   in the legacy compatibility string -- the decoder configuration and the macro channels
//!   among them -- and its digest joins the session's `compositionDigest`.
//!
//! `fixtures/gameboy-legacy.json` is the rendered set with every digest, regenerated by the
//! `update_fixtures` example and read by `packages/session-types`.
//!
//! [`legacy-gameboy-v1`]: ../../../../docs/design/session-framework/legacy-gameboy-v1.md

use flybus::wire::{ArtifactRef, Fields};
use serde_json::Value;

use crate::canonical;
use crate::extensions::{MAX_SLOTS, ROLLBACK_POLICY, SLOTS_CAPABILITY};
use crate::scalar::{
    DomainType, RationalNs, Result, SchemaRef, TypedValue, bounded_string, enumeration, err,
    is_digest, is_id, obj, require_unique, wire_err,
};
use crate::schema::{FieldSchema, TypeSchema, opt, req};
use crate::workers::AssetRef;

// ---------------------------------------------------------------------------------------------
// Constants of the legacy profile

/// The legacy profile id.
pub const PROFILE_ID: &str = "gameboy-legacy-fafb-v783-v1";
/// The dataset the profile is pinned to.
pub const DATASET_ID: &str = "fafb-v783";
/// The dataset fingerprint schema: the seven SHA-256 digests joined with `:`.
pub const FINGERPRINT_SCHEMA: u64 = 1;
/// Today's schema-1 fingerprint of `data/fafb-v783`, byte for byte what
/// `flybrain_core::dataset::fingerprint_dataset` computes and what segment 2 of the legacy
/// compatibility string carries. `flysim`'s `legacy_profile_identity` test recomputes it from
/// the committed dataset.
pub const FAFB_V783_FINGERPRINT: &str = "75ba5d3536a2862fdb9f4ef1a76b96fe099a7201ac737f0cf53fe4c5ad4183f3:\
1657ba7716494c9db95a13b1527bc129226363f99b395774de1f76ff28571f0e:\
63b1acb26272edccdcfacf3c2ff58069e0cefaa84451429c989258bafaeae1d5:\
f567d7f07227e71c0df2ab4e6510f3a3f79e51b675095792e16d216d74b7b5b7:\
ece0b5e76d1884dd2f3ff6e0362bc284febe205ac1ce07fdab5009942ddffb62:\
b8c33144d4cec31c3ac4b6091ef1f4207f567c4f710f7c13fd2dc47c44c2b634:\
dbbafc044cd50aad7b792615988ff6d9991c846cc3d8b2eafc86b7c357b5eefc";
/// The pinned default kernel version (CLAUDE.md): unchanged by this profile.
pub const KERNEL_VERSION: &str = "lif-1ms-f64-v2";
/// The pinned default plasticity version: unchanged by this profile.
pub const PLASTICITY_VERSION: &str = "fly-kc-mbon-rstdp-v2";
/// Warm-up with learning disabled on a fresh start, in brain milliseconds.
pub const WARMUP_MS: u64 = 2_500;
/// The one stimulus kind: the reward-population pulse that both sugar and task reward events
/// drive through `stimulate(durationMs)`.
pub const STIMULUS_REWARD_PULSE: &str = "reward-pulse";
/// The legacy exception the profile declares rather than repairs: the `macro_*` roles are
/// merged after the fingerprint is taken (`docs/design/malecns-modular-sessions.md` 2.2).
pub const EXCEPTION_MACRO_ROLES: &str = "macro-roles-outside-fingerprint";
/// The profile document's AssetRef format.
pub const PROFILE_FORMAT: &str = "fly-profile-v1";

/// The sensory view: the LCD, native size.
pub const VIEW_ID: &str = "lcd";
pub const VIEW_WIDTH: u64 = 160;
pub const VIEW_HEIGHT: u64 = 144;

/// The joypad, in the bit order of `GAMEBOY_BUTTON_BITS` (`docs/readout.md`).
pub const GAMEBOY_BUTTONS: [&str; 8] = ["up", "down", "left", "right", "a", "b", "start", "select"];

/// The memory image is the whole CPU address space, `$0000..=$FFFF`.
pub const MEMORY_IMAGE_BYTES: u64 = 65_536;

/// The executor extension.
pub const EXECUTOR_ID: &str = "pokered-macros-v1";
/// The restore semantics the composition declares.
pub const RESTORE_SEMANTICS: &str = "legacy-transient-reset";
/// The checkpoint format of record until RETIRE-01.
pub const CHECKPOINT_FORMAT_OF_RECORD: &str = "FLYSIM01";
/// The scheduler: the legacy composition runs in lockstep-v1.
pub const SCHEDULER: &str = "lockstep-v1";
/// The environment's setup scaffold: one frame with no button down before `O[0]`.
pub const SETUP_FRAMES: u64 = 1;
/// Macro channels in one decoder configuration (the 64-role limit).
pub const MAX_MACRO_CHANNELS: usize = 64;
/// The legacy compatibility string is 648 bytes today; bounded so a declaration stays small.
pub const MAX_COMPATIBILITY_BYTES: usize = 1_024;

/// One Game Boy frame, 70224 cycles of a 4194304 Hz clock, in nanoseconds:
/// `8572265625/512` exactly. The legacy `f64` constant `1000 / (4194304 / 70224)` is exactly
/// `548625/32768` ms, which is this value, so the legacy accumulator and the rational one of
/// `step-v1` section 5 produce the same ticks and remainders (`legacy-gameboy-v1` section 3).
pub fn step_duration() -> RationalNs {
    RationalNs::new(8_572_265_625, 512).expect("the Game Boy frame is a reduced rational")
}

/// One model tick: 1 ms.
pub fn tick_duration() -> RationalNs {
    RationalNs::new(1_000_000, 1).expect("1 ms")
}

// ---------------------------------------------------------------------------------------------
// Payload schemas

/// A registered `TypedValue` payload schema.
#[derive(Clone, Copy, Debug)]
pub struct PayloadSchema {
    pub id: &'static str,
    pub version: u16,
    /// Where the schema is specified.
    pub source: &'static str,
    pub fields: &'static [FieldSchema],
}

impl PayloadSchema {
    /// The declaration the digest is taken over.
    pub fn declaration(&self) -> Value {
        obj(vec![
            ("registry", "fly-session-payload-schema-v1".into()),
            ("id", self.id.into()),
            ("version", Value::from(u64::from(self.version))),
            ("source", self.source.into()),
            ("fields", fields_json(self.fields)),
        ])
    }

    /// `SchemaRef` whose digest is the SHA-256 of the canonical declaration.
    pub fn schema_ref(&self) -> SchemaRef {
        let digest = canonical::digest_of(&self.declaration()).expect("canonicalizable");
        SchemaRef::new(self.id, self.version, &digest).expect("a registered schema is valid")
    }
}

fn fields_json(fields: &[FieldSchema]) -> Value {
    Value::Array(
        fields
            .iter()
            .map(|f| {
                obj(vec![
                    ("name", f.name.into()),
                    ("kind", f.kind.into()),
                    ("required", Value::Bool(f.required)),
                    ("constraint", f.constraint.into()),
                ])
            })
            .collect(),
    )
}

/// The readout context the task hands the decoder with every Prepare.
pub const READOUT_CONTEXT: PayloadSchema = PayloadSchema {
    id: "gameboy-readout-context-v1",
    version: 1,
    source: "legacy-gameboy-v1 5",
    fields: &[
        req(
            "boot",
            "bool",
            "the adapter's boot gate after the last transition: permissive Start/Select variant",
        ),
        req(
            "bound",
            "array<ChannelName>",
            "<= 64, unique, a subset of the composition's macroChannels in their order; [] in raw mode",
        ),
        opt(
            "location",
            "{area:int,x:int,y:int}|null",
            "each 0..=4294967295; the adapter's location after the last transition; null is no information",
        ),
    ],
};

/// The decision the agent returns from Prepare.
pub const CHANNELS: PayloadSchema = PayloadSchema {
    id: "gameboy-channels-v1",
    version: 1,
    source: "legacy-gameboy-v1 6",
    fields: &[
        req(
            "buttons",
            "array<{id:Id,down:bool}>",
            "exactly up,down,left,right,a,b,start,select in that order",
        ),
        opt(
            "macro",
            "ChannelName|null",
            "the macro-group channel active in this decode; one of the context's bound",
        ),
    ],
};

/// The controller schema of the one port.
pub const JOYPAD: PayloadSchema = PayloadSchema {
    id: "gameboy-joypad-v1",
    version: 1,
    source: "legacy-gameboy-v1 7",
    fields: &[req(
        "buttons",
        "const",
        "up,down,left,right,a,b,start,select; no axes; one port",
    )],
};

/// The inspection the environment returns with every observation.
pub const MEMORY_INSPECTION: PayloadSchema = PayloadSchema {
    id: "gameboy-memory-inspection-v1",
    version: 1,
    source: "legacy-gameboy-v1 8",
    fields: &[
        req(
            "memory",
            "ArtifactRef",
            "listed attachment; byteLength 65536; the CPU address space $0000..=$FFFF at this boundary, read-only",
        ),
        req(
            "romDigest",
            "Digest",
            "== EnvironmentDescriptor.contentDigest == the executor's rom AssetRef digest",
        ),
    ],
};

/// The outcome of an `EpisodeRequest` of kind `rollback`.
pub const ROLLBACK_REQUEST: PayloadSchema = PayloadSchema {
    id: "legacy-ratchet-rollback-v1",
    version: 1,
    source: "legacy-gameboy-v1 11",
    fields: &[
        req(
            "slotId",
            "Id",
            "one of the composition's declared slots, saved earlier",
        ),
        req("trigger", "RollbackTrigger", "stall or game-over"),
    ],
};

/// Every registered payload schema of the legacy composition.
pub const PAYLOAD_SCHEMAS: &[PayloadSchema] = &[
    READOUT_CONTEXT,
    CHANNELS,
    JOYPAD,
    MEMORY_INSPECTION,
    ROLLBACK_REQUEST,
];

/// The Rust type names of this module and what they are declared as in [`extension_set`]:
/// a payload schema id or a declaration name. Every readable type is either in the session
/// schema set or here, so none can ship outside a digest.
pub const EXTENSION_TYPES: &[(&str, &str)] = &[
    ("GameboyReadoutContext", "gameboy-readout-context-v1"),
    ("GameboyChannelsDecision", "gameboy-channels-v1"),
    ("GameboyMemoryInspection", "gameboy-memory-inspection-v1"),
    ("LegacyRatchetRollbackRequest", "legacy-ratchet-rollback-v1"),
    ("LegacyGameboyProfile", "LegacyGameboyProfile"),
    ("LegacyGameboyComposition", "LegacyGameboyComposition"),
];

/// The rollback triggers the ratchet has (`flybrain-gb` `ratchet.rs`).
pub const ROLLBACK_TRIGGERS: &[&str] = &["stall", "game-over"];
/// The macro modes a composition may run.
pub const MACRO_MODES: &[&str] = &["raw", "macros"];

// ---------------------------------------------------------------------------------------------
// Declarations

/// The profile document and the composition declaration, as rows.
pub const DECLARATIONS: &[TypeSchema] = &[
    TypeSchema {
        name: "LegacyGameboyProfile",
        source: "legacy-gameboy-v1 2",
        fields: &[
            req("profileId", "const", "\"gameboy-legacy-fafb-v783-v1\""),
            req("datasetId", "const", "\"fafb-v783\""),
            req("fingerprintSchema", "const", "1"),
            req(
                "datasetFingerprint",
                "string",
                "today's schema-1 fingerprint, seven digests joined with ':'",
            ),
            req("kernelVersion", "const", "\"lif-1ms-f64-v2\""),
            req("plasticityVersion", "const", "\"fly-kc-mbon-rstdp-v2\""),
            req("tickDuration", "RationalNs", "1000000/1"),
            req("warmupMs", "const", "2500"),
            req("view", "{viewId:Id,width:int,height:int}", "lcd, 160, 144"),
            req("supportedStimuli", "array<Id>", "[\"reward-pulse\"]"),
            req(
                "readoutContextSchema",
                "SchemaRef",
                "gameboy-readout-context-v1",
            ),
            req("decisionSchema", "SchemaRef", "gameboy-channels-v1"),
            req(
                "legacyExceptions",
                "array<Id>",
                "[\"macro-roles-outside-fingerprint\"]",
            ),
        ],
    },
    TypeSchema {
        name: "LegacyGameboyComposition",
        source: "legacy-gameboy-v1 12",
        fields: &[
            req("compositionId", "Id", ""),
            req("scheduler", "const", "\"lockstep-v1\""),
            req(
                "profile",
                "AssetRef",
                "format fly-profile-v1; digest == the legacy profile's",
            ),
            req(
                "executor",
                "{id:const,rom:AssetRef,adapter:Id,symbolProvenance:string,mode:MacroMode,macroChannels:array<ChannelName>}",
                "pokered-macros-v1; task and executor one object; macroChannels [] iff mode raw, else <= 64 unique in decoder order",
            ),
            req(
                "decoderConfigDigest",
                "Digest",
                "SHA-256 of the canonical gameboy-decoder-config-v1 form of the effective decoder configuration",
            ),
            req(
                "environment",
                "{extensions:array<Id>,slots:array<Id>,stepDuration:RationalNs,inspectionSchema:SchemaRef,controllerSchema:SchemaRef,setupFrames:const,audio:{sampleRate:int,channels:const}}",
                "[\"gameboy-slots-v1\"]; 1..=4 unique slots; 8572265625/512; memory inspection; joypad; 1 setup frame; 2 channels",
            ),
            req("episodePolicy", "const", "\"legacy-ratchet-rollback-v1\""),
            req("restore", "const", "\"legacy-transient-reset\""),
            req("checkpointFormatOfRecord", "const", "\"FLYSIM01\""),
            req(
                "flysimCompatibility",
                "string",
                "<= 1024 bytes; the FLYSIM01 string; its kernel, adapter, fingerprint, plasticity and pokered segments agree with this declaration",
            ),
        ],
    },
];

/// The whole extension set: payload schemas with their references, and the declaration rows.
pub fn extension_set() -> Value {
    let mut payloads: Vec<&PayloadSchema> = PAYLOAD_SCHEMAS.iter().collect();
    payloads.sort_by_key(|p| p.id);
    let mut declarations: Vec<&TypeSchema> = DECLARATIONS.iter().collect();
    declarations.sort_by_key(|d| d.name);
    obj(vec![
        ("contract", "fly-session-types/legacy-gameboy".into()),
        ("version", Value::from(1u64)),
        (
            "scalars",
            obj(vec![(
                "ChannelName",
                "^[a-z][a-z0-9_]{0,63}$: a decoder channel or rate-role name; not an Id, because the legacy role names carry '_'".into(),
            )]),
        ),
        (
            "enums",
            obj(vec![
                (
                    "MacroMode",
                    Value::Array(MACRO_MODES.iter().map(|m| (*m).into()).collect()),
                ),
                (
                    "RollbackTrigger",
                    Value::Array(ROLLBACK_TRIGGERS.iter().map(|m| (*m).into()).collect()),
                ),
            ]),
        ),
        (
            "payloadSchemas",
            Value::Array(
                payloads
                    .iter()
                    .map(|p| {
                        obj(vec![
                            ("declaration", p.declaration()),
                            ("schemaRef", p.schema_ref().to_json()),
                        ])
                    })
                    .collect(),
            ),
        ),
        (
            "declarations",
            Value::Array(
                declarations
                    .iter()
                    .map(|d| {
                        obj(vec![
                            ("name", d.name.into()),
                            ("source", d.source.into()),
                            ("fields", fields_json(d.fields)),
                        ])
                    })
                    .collect(),
            ),
        ),
    ])
}

/// SHA-256 of the canonical extension set.
pub fn extension_set_digest() -> String {
    canonical::digest_of(&extension_set()).expect("canonicalizable")
}

// ---------------------------------------------------------------------------------------------
// Scalars and helpers

/// `ChannelName`: a decoder channel or rate-role name, `^[a-z][a-z0-9_]{0,63}$`.
pub fn is_channel_name(s: &str) -> bool {
    let bytes = s.as_bytes();
    !bytes.is_empty()
        && bytes.len() <= 64
        && bytes[0].is_ascii_lowercase()
        && bytes
            .iter()
            .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || *b == b'_')
}

fn channel_list(f: &mut Fields<'_>, key: &'static str, hi: usize) -> Result<Vec<String>> {
    let items = f.array(key, 0, hi)?;
    let mut out = Vec::with_capacity(items.len());
    for item in items {
        match item.as_str() {
            Some(s) if is_channel_name(s) => out.push(s.to_owned()),
            _ => return err(format!("{key}: every entry must be a channel name")),
        }
    }
    require_unique(out.iter().map(String::as_str), key)?;
    Ok(out)
}

fn u32_int(f: &mut Fields<'_>, key: &'static str) -> Result<u32> {
    Ok(f.int(key, 0, u64::from(u32::MAX))? as u32)
}

fn exact(found: &str, expected: &str, what: &str) -> Result<()> {
    if found != expected {
        return err(format!("{what} must be {expected:?}, found {found:?}"));
    }
    Ok(())
}

fn id_array(f: &mut Fields<'_>, key: &'static str, lo: usize, hi: usize) -> Result<Vec<String>> {
    let ids = crate::scalar::id_list(f, key, lo, hi)?;
    require_unique(ids.iter().map(String::as_str), key)?;
    Ok(ids)
}

fn schema_matches(found: &SchemaRef, schema: &PayloadSchema, what: &str) -> Result<()> {
    if *found != schema.schema_ref() {
        return err(format!(
            "{what} must be the registered {} reference",
            schema.id
        ));
    }
    Ok(())
}

/// Reads a `TypedValue` of a registered schema, refusing any other reference.
fn typed<T: DomainType>(value: &TypedValue, schema: &PayloadSchema) -> Result<T> {
    schema_matches(&value.schema, schema, "TypedValue.schema")?;
    T::from_json(&value.value)
}

fn wrap<T: DomainType>(value: &T, schema: &PayloadSchema) -> TypedValue {
    TypedValue::new(schema.schema_ref(), value.to_json()).expect("a registered value fits")
}

// ---------------------------------------------------------------------------------------------
// gameboy-readout-context-v1

/// Where the player is: the adapter's `(area, x, y)`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Location {
    pub area: u32,
    pub x: u32,
    pub y: u32,
}

/// `gameboy-readout-context-v1`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ReadoutContext {
    pub boot: bool,
    pub bound: Vec<String>,
    pub location: Option<Location>,
}

impl ReadoutContext {
    pub fn from_typed(value: &TypedValue) -> Result<ReadoutContext> {
        typed(value, &READOUT_CONTEXT)
    }

    pub fn to_typed(&self) -> TypedValue {
        wrap(self, &READOUT_CONTEXT)
    }

    /// `bound` is a subset of the composition's macro channels, in their order.
    pub fn validate_against(&self, macro_channels: &[String]) -> Result<()> {
        self.validate()?;
        let mut cursor = 0;
        for channel in &self.bound {
            match macro_channels[cursor..].iter().position(|c| c == channel) {
                Some(offset) => cursor += offset + 1,
                None => {
                    return err(format!(
                        "ReadoutContext: bound channel {channel:?} is not a macro channel of the composition, or is out of order"
                    ));
                }
            }
        }
        Ok(())
    }
}

impl DomainType for ReadoutContext {
    const TYPE_NAME: &'static str = "GameboyReadoutContext";

    fn from_json(value: &Value) -> Result<ReadoutContext> {
        let mut f = Fields::new(value, "GameboyReadoutContext")?;
        let boot = f.boolean("boot")?;
        let bound = channel_list(&mut f, "bound", MAX_MACRO_CHANNELS)?;
        let location = match f.value("location")? {
            Value::Null => None,
            v => {
                let mut l = Fields::new(v, "GameboyReadoutContext.location")?;
                let area = u32_int(&mut l, "area")?;
                let x = u32_int(&mut l, "x")?;
                let y = u32_int(&mut l, "y")?;
                l.finish()?;
                Some(Location { area, x, y })
            }
        };
        f.finish()?;
        let c = ReadoutContext {
            boot,
            bound,
            location,
        };
        c.validate()?;
        Ok(c)
    }

    fn to_json(&self) -> Value {
        obj(vec![
            ("boot", Value::Bool(self.boot)),
            (
                "bound",
                Value::Array(self.bound.iter().map(|b| b.clone().into()).collect()),
            ),
            (
                "location",
                self.location.map_or(Value::Null, |l| {
                    obj(vec![
                        ("area", Value::from(l.area)),
                        ("x", Value::from(l.x)),
                        ("y", Value::from(l.y)),
                    ])
                }),
            ),
        ])
    }

    fn validate(&self) -> Result<()> {
        if self.bound.len() > MAX_MACRO_CHANNELS {
            return err("GameboyReadoutContext: at most 64 bound channels");
        }
        if let Some(bad) = self.bound.iter().find(|b| !is_channel_name(b)) {
            return err(format!(
                "GameboyReadoutContext: {bad:?} is not a channel name"
            ));
        }
        require_unique(
            self.bound.iter().map(String::as_str),
            "GameboyReadoutContext.bound",
        )
    }
}

// ---------------------------------------------------------------------------------------------
// gameboy-channels-v1

/// `gameboy-channels-v1`: the eight joypad channels and the macro group's active channel.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ChannelsDecision {
    /// In [`GAMEBOY_BUTTONS`] order.
    pub buttons: [bool; 8],
    pub macro_channel: Option<String>,
}

impl ChannelsDecision {
    pub fn from_typed(value: &TypedValue) -> Result<ChannelsDecision> {
        typed(value, &CHANNELS)
    }

    pub fn to_typed(&self) -> TypedValue {
        wrap(self, &CHANNELS)
    }

    /// The joypad mask, bit `i` for `GAMEBOY_BUTTONS[i]`.
    pub fn mask(&self) -> u8 {
        self.buttons.iter().enumerate().fold(
            0u8,
            |mask, (bit, down)| if *down { mask | (1 << bit) } else { mask },
        )
    }

    /// The macro group only ever activates a bound channel (`docs/readout.md`, "Macro group").
    pub fn validate_against(&self, context: &ReadoutContext) -> Result<()> {
        self.validate()?;
        if let Some(channel) = &self.macro_channel
            && !context.bound.contains(channel)
        {
            return err(format!(
                "GameboyChannelsDecision: macro {channel:?} is not bound in the decision context"
            ));
        }
        Ok(())
    }
}

impl DomainType for ChannelsDecision {
    const TYPE_NAME: &'static str = "GameboyChannelsDecision";

    fn from_json(value: &Value) -> Result<ChannelsDecision> {
        let mut f = Fields::new(value, "GameboyChannelsDecision")?;
        let items = f.array("buttons", 8, 8)?;
        let mut buttons = [false; 8];
        for (index, item) in items.iter().enumerate() {
            let mut b = Fields::new(item, "GameboyChannelsDecision.buttons")?;
            let id = b.id("id")?;
            let down = b.boolean("down")?;
            b.finish()?;
            if id != GAMEBOY_BUTTONS[index] {
                return err(format!(
                    "GameboyChannelsDecision: buttons must list {} in that order",
                    GAMEBOY_BUTTONS.join(",")
                ));
            }
            buttons[index] = down;
        }
        let macro_channel = match f.value("macro")? {
            Value::Null => None,
            Value::String(s) if is_channel_name(s) => Some(s.clone()),
            _ => return err("GameboyChannelsDecision: macro must be null or a channel name"),
        };
        f.finish()?;
        let d = ChannelsDecision {
            buttons,
            macro_channel,
        };
        d.validate()?;
        Ok(d)
    }

    fn to_json(&self) -> Value {
        obj(vec![
            (
                "buttons",
                Value::Array(
                    GAMEBOY_BUTTONS
                        .iter()
                        .zip(self.buttons)
                        .map(|(id, down)| obj(vec![("id", (*id).into()), ("down", down.into())]))
                        .collect(),
                ),
            ),
            (
                "macro",
                self.macro_channel
                    .clone()
                    .map_or(Value::Null, Value::String),
            ),
        ])
    }

    fn validate(&self) -> Result<()> {
        if let Some(channel) = &self.macro_channel
            && !is_channel_name(channel)
        {
            return err("GameboyChannelsDecision: macro must be a channel name");
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------------------------
// gameboy-memory-inspection-v1

/// `gameboy-memory-inspection-v1`: the per-boundary memory image and the ROM it runs.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct MemoryInspection {
    pub memory: ArtifactRef,
    pub rom_digest: String,
}

impl MemoryInspection {
    pub fn from_typed(value: &TypedValue) -> Result<MemoryInspection> {
        typed(value, &MEMORY_INSPECTION)
    }

    pub fn to_typed(&self) -> TypedValue {
        wrap(self, &MEMORY_INSPECTION)
    }

    /// The ROM the executor reads is the content the environment runs.
    pub fn validate_against(&self, content_digest: &str, rom: &AssetRef) -> Result<()> {
        self.validate()?;
        if self.rom_digest != content_digest || rom.digest != content_digest {
            return err(
                "GameboyMemoryInspection: romDigest, the environment contentDigest and the executor's rom must agree",
            );
        }
        Ok(())
    }
}

impl DomainType for MemoryInspection {
    const TYPE_NAME: &'static str = "GameboyMemoryInspection";

    fn from_json(value: &Value) -> Result<MemoryInspection> {
        let mut f = Fields::new(value, "GameboyMemoryInspection")?;
        let memory = ArtifactRef::from_json(f.value("memory")?)?;
        let rom_digest = f.string("romDigest")?.to_owned();
        f.finish()?;
        let i = MemoryInspection { memory, rom_digest };
        i.validate()?;
        Ok(i)
    }

    fn to_json(&self) -> Value {
        obj(vec![
            ("memory", self.memory.to_json()),
            ("romDigest", self.rom_digest.clone().into()),
        ])
    }

    fn validate(&self) -> Result<()> {
        if self.memory.byte_length != MEMORY_IMAGE_BYTES {
            return err(format!(
                "GameboyMemoryInspection: the memory image is exactly {MEMORY_IMAGE_BYTES} bytes, found {}",
                self.memory.byte_length
            ));
        }
        if !is_digest(&self.rom_digest) {
            return err("GameboyMemoryInspection: romDigest must be 64 lowercase hex digits");
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------------------------
// legacy-ratchet-rollback-v1 (EpisodeRequest.outcome)

/// The outcome of an `EpisodeRequest` of kind `rollback`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RollbackRequest {
    pub slot_id: String,
    pub trigger: String,
}

impl RollbackRequest {
    pub fn from_typed(value: &TypedValue) -> Result<RollbackRequest> {
        typed(value, &ROLLBACK_REQUEST)
    }

    pub fn to_typed(&self) -> TypedValue {
        wrap(self, &ROLLBACK_REQUEST)
    }
}

impl DomainType for RollbackRequest {
    const TYPE_NAME: &'static str = "LegacyRatchetRollbackRequest";

    fn from_json(value: &Value) -> Result<RollbackRequest> {
        let mut f = Fields::new(value, "LegacyRatchetRollbackRequest")?;
        let slot_id = f.id("slotId")?;
        let trigger = enumeration(&mut f, "trigger", ROLLBACK_TRIGGERS)?;
        f.finish()?;
        let r = RollbackRequest { slot_id, trigger };
        r.validate()?;
        Ok(r)
    }

    fn to_json(&self) -> Value {
        obj(vec![
            ("slotId", self.slot_id.clone().into()),
            ("trigger", self.trigger.clone().into()),
        ])
    }

    fn validate(&self) -> Result<()> {
        if !is_id(&self.slot_id) {
            return err("LegacyRatchetRollbackRequest: slotId is not a valid id");
        }
        if !ROLLBACK_TRIGGERS.contains(&self.trigger.as_str()) {
            return err("LegacyRatchetRollbackRequest: trigger must be stall or game-over");
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------------------------
// The legacy profile

/// The legacy profile document. There is exactly one: every field is fixed, so the document
/// and its digest are constants of this contract, and a different value is a different
/// profile that needs its own id.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LegacyProfile {
    pub dataset_fingerprint: String,
    pub readout_context_schema: SchemaRef,
    pub decision_schema: SchemaRef,
}

/// The one legacy profile.
pub fn legacy_profile() -> LegacyProfile {
    LegacyProfile {
        dataset_fingerprint: FAFB_V783_FINGERPRINT.to_owned(),
        readout_context_schema: READOUT_CONTEXT.schema_ref(),
        decision_schema: CHANNELS.schema_ref(),
    }
}

/// SHA-256 of the legacy profile's canonical JSON: its `AssetRef.digest`.
pub fn profile_digest() -> String {
    canonical::digest_of(&legacy_profile().to_json()).expect("canonicalizable")
}

/// The canonical byte length of the profile document: its `AssetRef.byteLength`.
pub fn profile_byte_length() -> u64 {
    canonical::canonicalize(&legacy_profile().to_json())
        .expect("canonicalizable")
        .len() as u64
}

/// The `AssetRef` naming the profile document.
pub fn profile_asset_ref() -> AssetRef {
    AssetRef {
        id: PROFILE_ID.to_owned(),
        digest: profile_digest(),
        byte_length: profile_byte_length(),
        format: PROFILE_FORMAT.to_owned(),
    }
}

impl DomainType for LegacyProfile {
    const TYPE_NAME: &'static str = "LegacyGameboyProfile";

    fn from_json(value: &Value) -> Result<LegacyProfile> {
        let mut f = Fields::new(value, "LegacyGameboyProfile")?;
        exact(f.string("profileId")?, PROFILE_ID, "profileId")?;
        exact(f.string("datasetId")?, DATASET_ID, "datasetId")?;
        f.int("fingerprintSchema", FINGERPRINT_SCHEMA, FINGERPRINT_SCHEMA)?;
        let dataset_fingerprint = f.string("datasetFingerprint")?.to_owned();
        exact(f.string("kernelVersion")?, KERNEL_VERSION, "kernelVersion")?;
        exact(
            f.string("plasticityVersion")?,
            PLASTICITY_VERSION,
            "plasticityVersion",
        )?;
        let tick = RationalNs::from_json(f.value("tickDuration")?)?;
        if tick != tick_duration() {
            return err("LegacyGameboyProfile: tickDuration must be 1 ms (1000000/1)");
        }
        f.int("warmupMs", WARMUP_MS, WARMUP_MS)?;
        {
            let mut v = Fields::new(f.value("view")?, "LegacyGameboyProfile.view")?;
            exact(&v.id("viewId")?, VIEW_ID, "view.viewId")?;
            v.int("width", VIEW_WIDTH, VIEW_WIDTH)?;
            v.int("height", VIEW_HEIGHT, VIEW_HEIGHT)?;
            v.finish()?;
        }
        let stimuli = id_array(&mut f, "supportedStimuli", 1, 1)?;
        exact(&stimuli[0], STIMULUS_REWARD_PULSE, "supportedStimuli[0]")?;
        let readout_context_schema = SchemaRef::from_json(f.value("readoutContextSchema")?)?;
        let decision_schema = SchemaRef::from_json(f.value("decisionSchema")?)?;
        let exceptions = id_array(&mut f, "legacyExceptions", 1, 1)?;
        exact(&exceptions[0], EXCEPTION_MACRO_ROLES, "legacyExceptions[0]")?;
        f.finish()?;
        let p = LegacyProfile {
            dataset_fingerprint,
            readout_context_schema,
            decision_schema,
        };
        p.validate()?;
        Ok(p)
    }

    fn to_json(&self) -> Value {
        obj(vec![
            ("profileId", PROFILE_ID.into()),
            ("datasetId", DATASET_ID.into()),
            ("fingerprintSchema", Value::from(FINGERPRINT_SCHEMA)),
            (
                "datasetFingerprint",
                self.dataset_fingerprint.clone().into(),
            ),
            ("kernelVersion", KERNEL_VERSION.into()),
            ("plasticityVersion", PLASTICITY_VERSION.into()),
            ("tickDuration", tick_duration().to_json()),
            ("warmupMs", Value::from(WARMUP_MS)),
            (
                "view",
                obj(vec![
                    ("viewId", VIEW_ID.into()),
                    ("width", Value::from(VIEW_WIDTH)),
                    ("height", Value::from(VIEW_HEIGHT)),
                ]),
            ),
            (
                "supportedStimuli",
                Value::Array(vec![STIMULUS_REWARD_PULSE.into()]),
            ),
            (
                "readoutContextSchema",
                self.readout_context_schema.to_json(),
            ),
            ("decisionSchema", self.decision_schema.to_json()),
            (
                "legacyExceptions",
                Value::Array(vec![EXCEPTION_MACRO_ROLES.into()]),
            ),
        ])
    }

    fn validate(&self) -> Result<()> {
        if self.dataset_fingerprint != FAFB_V783_FINGERPRINT {
            return err(
                "LegacyGameboyProfile: datasetFingerprint must be today's fafb-v783 schema-1 fingerprint; another fingerprint is another profile",
            );
        }
        schema_matches(
            &self.readout_context_schema,
            &READOUT_CONTEXT,
            "LegacyGameboyProfile.readoutContextSchema",
        )?;
        schema_matches(
            &self.decision_schema,
            &CHANNELS,
            "LegacyGameboyProfile.decisionSchema",
        )
    }
}

// ---------------------------------------------------------------------------------------------
// The legacy composition

/// The executor block of the composition.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ExecutorDeclaration {
    pub rom: AssetRef,
    pub adapter: String,
    pub symbol_provenance: String,
    pub mode: String,
    pub macro_channels: Vec<String>,
}

/// The environment block of the composition.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct EnvironmentDeclaration {
    pub slots: Vec<String>,
    pub audio_sample_rate: u64,
}

/// `LegacyGameboyComposition`: what the legacy composition runs, beyond the profile. Its
/// digest joins the session's `compositionDigest`; the FLYSIM01 compatibility string is
/// recorded beside it, unchanged.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LegacyComposition {
    pub composition_id: String,
    pub profile: AssetRef,
    pub executor: ExecutorDeclaration,
    pub decoder_config_digest: String,
    pub environment: EnvironmentDeclaration,
    pub flysim_compatibility: String,
}

impl LegacyComposition {
    /// SHA-256 of the canonical declaration: the line `declaration=<digest>` of the
    /// session's composition digest (`legacy-gameboy-v1` section 12).
    pub fn digest(&self) -> Result<String> {
        canonical::digest_of(&self.to_json())
    }
}

impl DomainType for LegacyComposition {
    const TYPE_NAME: &'static str = "LegacyGameboyComposition";

    fn from_json(value: &Value) -> Result<LegacyComposition> {
        let mut f = Fields::new(value, "LegacyGameboyComposition")?;
        let composition_id = f.id("compositionId")?;
        exact(f.string("scheduler")?, SCHEDULER, "scheduler")?;
        let profile = AssetRef::from_json(f.value("profile")?)?;
        let executor = {
            let mut e = Fields::new(f.value("executor")?, "LegacyGameboyComposition.executor")?;
            exact(e.string("id")?, EXECUTOR_ID, "executor.id")?;
            let rom = AssetRef::from_json(e.value("rom")?)?;
            let adapter = e.id("adapter")?;
            let symbol_provenance = bounded_string(&mut e, "symbolProvenance", 64)?;
            let mode = enumeration(&mut e, "mode", MACRO_MODES)?;
            let macro_channels = channel_list(&mut e, "macroChannels", MAX_MACRO_CHANNELS)?;
            e.finish()?;
            ExecutorDeclaration {
                rom,
                adapter,
                symbol_provenance,
                mode,
                macro_channels,
            }
        };
        let decoder_config_digest = f.string("decoderConfigDigest")?.to_owned();
        let environment = {
            let mut e = Fields::new(
                f.value("environment")?,
                "LegacyGameboyComposition.environment",
            )?;
            let extensions = id_array(&mut e, "extensions", 1, 1)?;
            exact(
                &extensions[0],
                SLOTS_CAPABILITY,
                "environment.extensions[0]",
            )?;
            let slots = id_array(&mut e, "slots", 1, MAX_SLOTS)?;
            let step = RationalNs::from_json(e.value("stepDuration")?)?;
            if step != step_duration() {
                return err(
                    "LegacyGameboyComposition: environment.stepDuration must be one Game Boy frame, 8572265625/512 ns",
                );
            }
            schema_matches(
                &SchemaRef::from_json(e.value("inspectionSchema")?)?,
                &MEMORY_INSPECTION,
                "environment.inspectionSchema",
            )?;
            schema_matches(
                &SchemaRef::from_json(e.value("controllerSchema")?)?,
                &JOYPAD,
                "environment.controllerSchema",
            )?;
            e.int("setupFrames", SETUP_FRAMES, SETUP_FRAMES)?;
            let audio_sample_rate = {
                let mut a = Fields::new(e.value("audio")?, "environment.audio")?;
                let rate = a.int("sampleRate", 8_000, 192_000)?;
                a.int("channels", 2, 2)?;
                a.finish()?;
                rate
            };
            e.finish()?;
            EnvironmentDeclaration {
                slots,
                audio_sample_rate,
            }
        };
        exact(f.string("episodePolicy")?, ROLLBACK_POLICY, "episodePolicy")?;
        exact(f.string("restore")?, RESTORE_SEMANTICS, "restore")?;
        exact(
            f.string("checkpointFormatOfRecord")?,
            CHECKPOINT_FORMAT_OF_RECORD,
            "checkpointFormatOfRecord",
        )?;
        let flysim_compatibility = f.string("flysimCompatibility")?.to_owned();
        f.finish()?;
        let c = LegacyComposition {
            composition_id,
            profile,
            executor,
            decoder_config_digest,
            environment,
            flysim_compatibility,
        };
        c.validate()?;
        Ok(c)
    }

    fn to_json(&self) -> Value {
        obj(vec![
            ("compositionId", self.composition_id.clone().into()),
            ("scheduler", SCHEDULER.into()),
            ("profile", self.profile.to_json()),
            (
                "executor",
                obj(vec![
                    ("id", EXECUTOR_ID.into()),
                    ("rom", self.executor.rom.to_json()),
                    ("adapter", self.executor.adapter.clone().into()),
                    (
                        "symbolProvenance",
                        self.executor.symbol_provenance.clone().into(),
                    ),
                    ("mode", self.executor.mode.clone().into()),
                    (
                        "macroChannels",
                        Value::Array(
                            self.executor
                                .macro_channels
                                .iter()
                                .map(|c| c.clone().into())
                                .collect(),
                        ),
                    ),
                ]),
            ),
            (
                "decoderConfigDigest",
                self.decoder_config_digest.clone().into(),
            ),
            (
                "environment",
                obj(vec![
                    ("extensions", Value::Array(vec![SLOTS_CAPABILITY.into()])),
                    (
                        "slots",
                        Value::Array(
                            self.environment
                                .slots
                                .iter()
                                .map(|s| s.clone().into())
                                .collect(),
                        ),
                    ),
                    ("stepDuration", step_duration().to_json()),
                    ("inspectionSchema", MEMORY_INSPECTION.schema_ref().to_json()),
                    ("controllerSchema", JOYPAD.schema_ref().to_json()),
                    ("setupFrames", Value::from(SETUP_FRAMES)),
                    (
                        "audio",
                        obj(vec![
                            (
                                "sampleRate",
                                Value::from(self.environment.audio_sample_rate),
                            ),
                            ("channels", Value::from(2u64)),
                        ]),
                    ),
                ]),
            ),
            ("episodePolicy", ROLLBACK_POLICY.into()),
            ("restore", RESTORE_SEMANTICS.into()),
            (
                "checkpointFormatOfRecord",
                CHECKPOINT_FORMAT_OF_RECORD.into(),
            ),
            (
                "flysimCompatibility",
                self.flysim_compatibility.clone().into(),
            ),
        ])
    }

    fn validate(&self) -> Result<()> {
        if !is_id(&self.composition_id) {
            return err("LegacyGameboyComposition: compositionId is not a valid id");
        }
        self.profile.validate()?;
        if self.profile.format != PROFILE_FORMAT || self.profile.digest != profile_digest() {
            return err(
                "LegacyGameboyComposition: profile must name the legacy profile document (format fly-profile-v1, its digest)",
            );
        }
        self.executor.rom.validate()?;
        if !is_id(&self.executor.adapter) {
            return err("LegacyGameboyComposition: executor.adapter is not a valid id");
        }
        match self.executor.mode.as_str() {
            "raw" if !self.executor.macro_channels.is_empty() => {
                return err("LegacyGameboyComposition: raw mode deals no macro channels");
            }
            "macros" if self.executor.macro_channels.is_empty() => {
                return err("LegacyGameboyComposition: macros mode needs its macro channels");
            }
            "raw" | "macros" => {}
            _ => return err("LegacyGameboyComposition: executor.mode must be raw or macros"),
        }
        if let Some(bad) = self
            .executor
            .macro_channels
            .iter()
            .find(|c| !is_channel_name(c))
        {
            return err(format!(
                "LegacyGameboyComposition: {bad:?} is not a channel name"
            ));
        }
        require_unique(
            self.executor.macro_channels.iter().map(String::as_str),
            "executor.macroChannels",
        )?;
        if !is_digest(&self.decoder_config_digest) {
            return err(
                "LegacyGameboyComposition: decoderConfigDigest must be 64 lowercase hex digits",
            );
        }
        if self.environment.slots.is_empty() || self.environment.slots.len() > MAX_SLOTS {
            return err("LegacyGameboyComposition: 1..=4 slots");
        }
        require_unique(
            self.environment.slots.iter().map(String::as_str),
            "environment.slots",
        )?;
        self.validate_compatibility()
    }
}

impl LegacyComposition {
    /// The FLYSIM01 string is recorded, not reinterpreted; but the segments that name what
    /// this declaration also names must agree with it, so the two cannot describe two flies.
    fn validate_compatibility(&self) -> Result<()> {
        let text = &self.flysim_compatibility;
        if text.is_empty() || text.len() > MAX_COMPATIBILITY_BYTES {
            return err("LegacyGameboyComposition: flysimCompatibility must be 1..=1024 bytes");
        }
        let segments: Vec<&str> = text.split('/').collect();
        let pokered = format!("pokered:{}", self.executor.symbol_provenance);
        let agrees = segments.len() >= 6
            && segments[0] == KERNEL_VERSION
            && segments[1] == self.executor.adapter
            && segments[2] == FAFB_V783_FINGERPRINT
            && segments[3] == PLASTICITY_VERSION
            && segments[5] == pokered;
        if !agrees {
            return Err(wire_err(
                "LegacyGameboyComposition: flysimCompatibility's kernel, adapter, fingerprint, plasticity and pokered segments must agree with the declaration",
            ));
        }
        Ok(())
    }
}
